"""Golden parity snapshots for the legacy ``matching`` scorer.

These freeze the EXACT integer/boolean/string outputs of the current
``tuneshift.matching`` public surface. They are a *refactor change-detector*,
not a correctness oracle: they must keep passing while ``matching.py`` is split
into the ``matching/`` package (byte-parity), and are deliberately re-baselined
ONLY in the scoring-change chunks (intent fidelity, availability, locks) with a
human-reviewed diff.

Expected values were generated by running the current functions once and
freezing the results as literals.
"""
import pytest

from tuneshift import matching as m

NORMALIZE_TITLE = [
    ('Bohemian Rhapsody', 'bohemian rhapsody'),
    ('Bohemian Rhapsody (2011 Remaster)', 'bohemian rhapsody'),
    ('Song (Deluxe Edition)', 'song'),
    ('Track (feat. Someone)', 'track'),
    ('Track [ft. Someone]', 'track'),
    ('Song feat. Guest', 'song'),
    ('The Song', 'the song'),
    ('Café del Mar', 'café del mar'),
    ('“Quoted” Title…', '"quoted" title...'),
    ('', ''),
    ('Anniversary (40th Anniversary Edition)', 'anniversary (40th anniversary edition)'),
    ('Mix (2019 Remix)', 'mix'),
    ("Taylor's Version (Taylor's Version)", "taylor's version"),
]

NORMALIZE_ARTIST = [
    ('P!nk', 'p!nk'),
    ('Pink', 'pink'),
    ('The Beatles', 'beatles'),
    ('Beatles', 'beatles'),
    ('Simon & Garfunkel', 'simon and garfunkel'),
    ('Simon and Garfunkel', 'simon and garfunkel'),
    ('Tyler, The Creator', 'tyler the creator'),
    ('Artist feat. Guest', 'artist'),
    ('Artist (feat. Guest)', 'artist'),
    ('', ''),
    ('A$AP Rocky', 'a$ap rocky'),
    ('Beyoncé', 'beyoncé'),
]

IS_REMASTER = [
    ('Abbey Road (Remastered)', True),
    ('Abbey Road', False),
    ('', False),
    ('1989 remaster edition', True),
]

SCORE_MATCH = [
    (('Bohemian Rhapsody', 'Queen', 'A Night at the Opera', 'Bohemian Rhapsody', 'Queen', 'A Night at the Opera'), 100),
    (('Bohemian Rhapsody', 'Queen', 'A Night at the Opera', 'Bohemian Rhapsody', 'Queen', 'Greatest Hits'), 80),
    (('Bohemian Rhapsody', 'Queen', None, 'Bohemian Rhapsody', 'Queen', 'Whatever'), 80),
    (('Song Title', 'Artist', 'Album', 'Song Titel', 'Artist', 'Album'), 80),
    (('Song Title Here', 'Artist', 'Album', 'Different Song X', 'Artist', 'Album'), 50),
    (('Crazy', 'Britney Spears', None, '(You Drive Me) Crazy', 'Britney Spears', 'X'), 30),
    (('Track', 'Alpha Band', None, 'Track', 'Beta Group', 'X'), 32),
    (('Track', 'Robert Plant', None, 'Track', 'Robert Plante', 'X'), 75),
    (('Track', 'John Smith', None, 'Track', 'Jon Smith', 'X'), 75),
    (('Track', 'ABCDEF', None, 'Track', 'ABCXYZ', 'X'), 50),
    (('Song', 'Artist', 'The Album Name', 'Song', 'Artist', 'The Album Nam'), 90),
    (('Song', 'Artist', 'Completely Different', 'Song', 'Artist', 'Nothing Alike Here'), 80),
]

VERSION_PENALTY = [
    (('Song (Karaoke Version)', ''), 50),
    (('Song - Instrumental', ''), 50),
    (('Song (Live)', ''), 20),
    (('Song (Remix)', ''), 20),
    (('Song (Tribute)', ''), 20),
    (('Song (Radio Edit)', ''), 20),
    (('Song', 'Greatest Hits'), 15),
    (('Song (Acoustic)', ''), 10),
    (('Song', 'Album (Remastered)'), 10),
    (('Song', 'Album (Deluxe)'), 5),
    (('Song (Live)', 'Album (Remastered)'), 30),
    (('Plain Song', 'Plain Album'), 0),
    (('Song (Karaoke) (Live)', 'Deluxe'), 75),
]

DURATION_PENALTY = [
    ((None, 200, None), 0),
    ((200, None, None), 0),
    ((200, 200, None), 0),
    ((500, 200, None), 20),
    ((340, 200, None), 15),
    ((300, 200, None), 10),
    ((280, 200, None), 0),
    ((90, 200, None), 20),
    ((125, 200, None), 15),
    ((145, 200, None), 10),
    ((160, 200, None), 0),
    ((250, None, [300, 200, 210]), 0),
    ((200, 30, None), 0),
]

DURATION_PROXIMITY = [
    ((None, 200), 0),
    ((200, None), 0),
    ((200, 20), 0),
    ((200, 200), 10),
    ((208, 200), 10),
    ((220, 200), 5),
    ((260, 200), 0),
]

SCORE_MATCH_WITH_VERSION = [
    (('Song', 'Artist', 'Album', 'Song', 'Artist', 'Album', None, None, None), 100),
    # RE-BASELINED (Chunk 4 intent fidelity, 2026-07-02): a studio source no
    # longer *tolerates* a live candidate with a 30 score — the source-aware
    # recording verdict REJECTs a live take for a studio master, flooring to 0.
    (('Song', 'Artist', 'Album', 'Song (Live)', 'Artist', 'Album', None, None, None), 0),
    (('Song', 'Artist', 'Album', 'Song', 'Artist', 'Album', 500, 200, None), 80),
    (('Song', 'Artist', 'Album', 'Song (Karaoke)', 'Artist', 'Album', None, None, None), 0),
]

CLASSIFY_RESULTS = [
    ([], 'not_found'),
    ([40, 30], 'not_found'),
    ([85, 60], 'high'),
    ([85, 75], 'ambiguous'),
    ([55, 52], 'ambiguous'),
    ([90], 'high'),
    ([49], 'not_found'),
]


@pytest.mark.parametrize("value, expected", NORMALIZE_TITLE)
def test_normalize_title_parity(value, expected):
    assert m.normalize_title(value) == expected


@pytest.mark.parametrize("value, expected", NORMALIZE_ARTIST)
def test_normalize_artist_parity(value, expected):
    assert m.normalize_artist(value) == expected


@pytest.mark.parametrize("value, expected", IS_REMASTER)
def test_is_remaster_parity(value, expected):
    assert m.is_remaster(value) == expected


@pytest.mark.parametrize("args, expected", SCORE_MATCH)
def test_score_match_parity(args, expected):
    assert m.score_match(*args) == expected


@pytest.mark.parametrize("args, expected", VERSION_PENALTY)
def test_version_penalty_parity(args, expected):
    assert m.version_penalty(*args) == expected


@pytest.mark.parametrize("args, expected", DURATION_PENALTY)
def test_duration_penalty_parity(args, expected):
    assert m.duration_penalty(*args) == expected


@pytest.mark.parametrize("args, expected", DURATION_PROXIMITY)
def test_duration_proximity_bonus_parity(args, expected):
    assert m.duration_proximity_bonus(*args) == expected


@pytest.mark.parametrize("args, expected", SCORE_MATCH_WITH_VERSION)
def test_score_match_with_version_parity(args, expected):
    assert m.score_match_with_version(*args) == expected


@pytest.mark.parametrize("scores, expected", CLASSIFY_RESULTS)
def test_classify_results_parity(scores, expected):
    assert m.classify_results(scores) == expected


def test_score_match_object_form_requires_track_like():
    """The object-form of score_match raises TypeError on non-track objects."""
    with pytest.raises(TypeError):
        m.score_match("not-a-track", "also-not")
